import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/SideBar";
import Footer from "@/components/footer/Footer";
import TopSection from "@/components/top-section/TopSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <TopSection />
        {children}
        <Footer />
      </body>
    </html>
  );
}
